name: app_brewery_tutorial
description: App Brewery Tutorial
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  audioplayers: ^0.13.1
  font_awesome_flutter: ^8.5.0
  rflutter_alert: ^1.0.3
  geolocator: ^5.1.4+1
  http: ^0.12.0+2
  flutter_spinkit: ^4.0.0
  animated_text_kit: ^1.3.1
  modal_progress_hud: ^0.1.3
  provider: ^3.1.0+1


  #firebase libs
  firebase_core: ^0.4.0+9
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.12.9+5


dev_dependencies:
  flutter_test:
    sdk: flutter
  #lint: ^0.3.2+dart205
  pedantic: ^1.8.0+1
flutter:
  uses-material-design: true
  assets:
    - images/
    - assets/
  fonts:
    - family: Lacquer
      fonts:
        - asset: fonts/Lacquer/Lacquer-Regular.ttf
    - family: SourceSansPro
      fonts:
        - asset: fonts/Source_Sans_Pro/SourceSansPro-Regular.ttf